/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registroUser;

import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author Alumno
 */
public class RegistroUser extends javax.swing.JFrame {

    private LinkedList<UsuarioBiblioteca> listaUsuarios;
    private UsuarioBiblioteca usuario;
    
    public RegistroUser() {
        initComponents();
        listaUsuarios=new  LinkedList<>();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AGREGAR1 = new javax.swing.JButton();
        SALIR = new javax.swing.JButton();
        iconoUser = new javax.swing.JLabel();
        lbTelefono = new javax.swing.JLabel();
        lbNombre1 = new javax.swing.JLabel();
        lbApellido1 = new javax.swing.JLabel();
        lbApellido2 = new javax.swing.JLabel();
        cmDia = new javax.swing.JComboBox<>();
        cmMes = new javax.swing.JComboBox<>();
        cmAnio = new javax.swing.JComboBox<>();
        lbCalle = new javax.swing.JLabel();
        lbContrasenia = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido1 = new javax.swing.JTextField();
        txtApellido2 = new javax.swing.JTextField();
        txtCalle = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        AGREGAR = new javax.swing.JButton();
        lbTitulo = new javax.swing.JLabel();
        MODIFICAR = new javax.swing.JButton();
        BUSCAR = new javax.swing.JButton();
        txtTelefono = new javax.swing.JTextField();
        LISTAR = new javax.swing.JButton();
        icono = new javax.swing.JLabel();

        AGREGAR1.setBackground(new java.awt.Color(0, 102, 204));
        AGREGAR1.setForeground(new java.awt.Color(255, 255, 255));
        AGREGAR1.setText("Agregar");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SALIR.setBackground(new java.awt.Color(0, 0, 102));
        SALIR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SALIR.setForeground(new java.awt.Color(255, 255, 255));
        SALIR.setText("Salir");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });
        getContentPane().add(SALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 70, 30));

        iconoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registroUser/User.png"))); // NOI18N
        getContentPane().add(iconoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 240, 260));

        lbTelefono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTelefono.setForeground(new java.awt.Color(255, 255, 255));
        lbTelefono.setText("Telefono");
        getContentPane().add(lbTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 90, 30));

        lbNombre1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbNombre1.setForeground(new java.awt.Color(255, 255, 255));
        lbNombre1.setText("Nombre");
        getContentPane().add(lbNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 70, 30));

        lbApellido1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbApellido1.setForeground(new java.awt.Color(255, 255, 255));
        lbApellido1.setText("Apellido1");
        getContentPane().add(lbApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 70, 30));

        lbApellido2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbApellido2.setForeground(new java.awt.Color(255, 255, 255));
        lbApellido2.setText("Apellido2");
        getContentPane().add(lbApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 70, 30));

        cmDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(cmDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        cmMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        getContentPane().add(cmMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        cmAnio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1865", "1866", "1867", "1868", "1869", "1870", "1871", "1872", "1873", "1874", "1875", "1876", "1877", "1878", "1879", "1880", "1881", "1882", "1883", "1884", "1885", "1886", "1887", "1888", "1889", "1890", "1891", "1892", "1893", "1894", "1895", "1896", "1897", "1898", "1899", "1900", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017" }));
        cmAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmAnioActionPerformed(evt);
            }
        });
        getContentPane().add(cmAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        lbCalle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbCalle.setForeground(new java.awt.Color(255, 255, 255));
        lbCalle.setText("Calle #");
        getContentPane().add(lbCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 70, 30));

        lbContrasenia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbContrasenia.setForeground(new java.awt.Color(255, 255, 255));
        lbContrasenia.setText("Usuario");
        getContentPane().add(lbContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 80, 30));

        txtNombre.setBackground(new java.awt.Color(0, 102, 204));
        txtNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 140, 30));

        txtApellido1.setBackground(new java.awt.Color(0, 102, 204));
        txtApellido1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtApellido1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 140, 30));

        txtApellido2.setBackground(new java.awt.Color(0, 102, 204));
        txtApellido2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtApellido2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 140, 30));

        txtCalle.setBackground(new java.awt.Color(0, 102, 204));
        txtCalle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCalle.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 140, 30));

        txtUser.setBackground(new java.awt.Color(0, 102, 204));
        txtUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtUser.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 160, 30));

        AGREGAR.setBackground(new java.awt.Color(0, 102, 204));
        AGREGAR.setForeground(new java.awt.Color(255, 255, 255));
        AGREGAR.setText("Agregar");
        AGREGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AGREGARActionPerformed(evt);
            }
        });
        getContentPane().add(AGREGAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 90, 30));

        lbTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbTitulo.setText("Registro de Usuarios");
        getContentPane().add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 240, 40));

        MODIFICAR.setBackground(new java.awt.Color(0, 102, 204));
        MODIFICAR.setForeground(new java.awt.Color(255, 255, 255));
        MODIFICAR.setText("Modificar");
        MODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODIFICARActionPerformed(evt);
            }
        });
        getContentPane().add(MODIFICAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 90, 30));

        BUSCAR.setBackground(new java.awt.Color(0, 102, 204));
        BUSCAR.setForeground(new java.awt.Color(255, 255, 255));
        BUSCAR.setText("Buscar");
        BUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUSCARActionPerformed(evt);
            }
        });
        getContentPane().add(BUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 90, 30));

        txtTelefono.setBackground(new java.awt.Color(0, 102, 204));
        txtTelefono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 140, 30));

        LISTAR.setBackground(new java.awt.Color(0, 102, 204));
        LISTAR.setForeground(new java.awt.Color(255, 255, 255));
        LISTAR.setText("Listar");
        LISTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LISTARActionPerformed(evt);
            }
        });
        getContentPane().add(LISTAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 90, 30));

        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registroUser/FondoAzul.png"))); // NOI18N
        getContentPane().add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 468, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SALIRActionPerformed

    private void AGREGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AGREGARActionPerformed

        UsuarioBiblioteca user = new UsuarioBiblioteca(txtNombre.getText(),
                txtApellido1.getText(), 
                txtApellido2.getText(),
                cmAnio.getSelectedItem().toString(), 
                cmMes.getSelectedItem().toString(), 
                cmDia.getSelectedItem().toString(),
                txtUser.getText(),txtCalle.getText(),
                txtTelefono.getText());
        
        listaUsuarios.add(user);
    }//GEN-LAST:event_AGREGARActionPerformed

    private void BUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUSCARActionPerformed
        String busqueda=JOptionPane.showInputDialog("Introdusca el usuario: ");
        
        UsuarioBiblioteca user=new UsuarioBiblioteca(); 
        
           user.setUsuario(busqueda);
      if  (listaUsuarios.contains(user)){
              int posicion=listaUsuarios.indexOf(user);              
              usuario=(UsuarioBiblioteca)listaUsuarios.get(posicion);
              //llenar todos los espacios 
              txtNombre.setText(usuario.getNombre());
              txtApellido1.setText(usuario.getApellido1());
              txtApellido2.setText(usuario.getApellido2());
              cmAnio.setSelectedItem(usuario.getAnio());
              cmMes.setSelectedItem(usuario.getMes());
              cmDia.setSelectedItem(usuario.getDia());
              txtTelefono.setText(usuario.getApellido2());
              
              //botones activados
              
              //actualizar ,remover 
                           
          }
          else{
              JOptionPane.showMessageDialog(null,"El usuario no esta ");
          }
    }//GEN-LAST:event_BUSCARActionPerformed

    private void MODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODIFICARActionPerformed
              txtNombre.setText(usuario.getNombre());
              txtApellido1.setText(usuario.getApellido1());
              txtApellido2.setText(usuario.getApellido2());
              cmAnio.setSelectedItem(usuario.getAnio());
              cmMes.setSelectedItem(usuario.getMes());
              cmDia.setSelectedItem(usuario.getDia());
              txtTelefono.setText(usuario.getApellido2());
    }//GEN-LAST:event_MODIFICARActionPerformed

    private void LISTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LISTARActionPerformed
        System.out.println(listaUsuarios);
    }//GEN-LAST:event_LISTARActionPerformed

    private void cmAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmAnioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AGREGAR;
    private javax.swing.JButton AGREGAR1;
    private javax.swing.JButton BUSCAR;
    private javax.swing.JButton LISTAR;
    private javax.swing.JButton MODIFICAR;
    private javax.swing.JButton SALIR;
    private javax.swing.JComboBox<String> cmAnio;
    private javax.swing.JComboBox<String> cmDia;
    private javax.swing.JComboBox<String> cmMes;
    private javax.swing.JLabel icono;
    private javax.swing.JLabel iconoUser;
    private javax.swing.JLabel lbApellido1;
    private javax.swing.JLabel lbApellido2;
    private javax.swing.JLabel lbCalle;
    private javax.swing.JLabel lbContrasenia;
    private javax.swing.JLabel lbNombre1;
    private javax.swing.JLabel lbTelefono;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtApellido2;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
