/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registroLibro;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import registroUser.UsuarioBiblioteca;

/**
 *
 * @author edwinjack
 */
public class RegistroLibro extends javax.swing.JFrame {

    private LinkedList<LibroBib> listaLibros;
    private LibroBib libro;
    
    public RegistroLibro() {
        initComponents();
        listaLibros=new  LinkedList<>();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TITULO = new javax.swing.JLabel();
        SALIR = new javax.swing.JButton();
        lbISBN = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        lbAutor = new javax.swing.JLabel();
        cmDia = new javax.swing.JComboBox<>();
        cmMes = new javax.swing.JComboBox<>();
        cmAnio = new javax.swing.JComboBox<>();
        lbFecha = new javax.swing.JLabel();
        lbEstatus = new javax.swing.JLabel();
        lbEdicion = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtEstatus = new javax.swing.JTextField();
        txtEdicion = new javax.swing.JTextField();
        AGREGAR = new javax.swing.JButton();
        BUSCAR = new javax.swing.JButton();
        MODIFICAR = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TITULO.setBackground(new java.awt.Color(255, 102, 102));
        TITULO.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        TITULO.setForeground(new java.awt.Color(255, 255, 255));
        TITULO.setText("Registro libros");
        getContentPane().add(TITULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 240, 40));

        SALIR.setBackground(new java.awt.Color(255, 102, 102));
        SALIR.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SALIR.setForeground(new java.awt.Color(255, 255, 255));
        SALIR.setText("SALIR");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });
        getContentPane().add(SALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, -1, -1));

        lbISBN.setBackground(new java.awt.Color(255, 102, 102));
        lbISBN.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbISBN.setForeground(new java.awt.Color(255, 255, 255));
        lbISBN.setText("ISBN");
        getContentPane().add(lbISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 90, 30));

        lbTitulo.setBackground(new java.awt.Color(255, 102, 102));
        lbTitulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbTitulo.setText("Titulo");
        getContentPane().add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 100, 40));

        lbAutor.setBackground(new java.awt.Color(255, 102, 102));
        lbAutor.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbAutor.setForeground(new java.awt.Color(255, 255, 255));
        lbAutor.setText("Autor");
        getContentPane().add(lbAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 100, 40));

        cmDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(cmDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 50, 30));

        cmMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        getContentPane().add(cmMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 90, 30));

        cmAnio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1865", "1866", "1867", "1868", "1869", "1870", "1871", "1872", "1873", "1874", "1875", "1876", "1877", "1878", "1879", "1880", "1881", "1882", "1883", "1884", "1885", "1886", "1887", "1888", "1889", "1890", "1891", "1892", "1893", "1894", "1895", "1896", "1897", "1898", "1899", "1900", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017" }));
        cmAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmAnioActionPerformed(evt);
            }
        });
        getContentPane().add(cmAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 60, 30));

        lbFecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbFecha.setForeground(new java.awt.Color(255, 255, 255));
        lbFecha.setText("Fecha de publicacion");
        getContentPane().add(lbFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 150, 30));

        lbEstatus.setBackground(new java.awt.Color(255, 102, 102));
        lbEstatus.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbEstatus.setForeground(new java.awt.Color(255, 255, 255));
        lbEstatus.setText("Estatus");
        getContentPane().add(lbEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 90, 40));

        lbEdicion.setBackground(new java.awt.Color(255, 102, 102));
        lbEdicion.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbEdicion.setForeground(new java.awt.Color(255, 255, 255));
        lbEdicion.setText("Edicion");
        getContentPane().add(lbEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 90, 40));

        txtISBN.setBackground(new java.awt.Color(204, 204, 255));
        txtISBN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtISBN.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 210, 30));

        txtTitulo.setBackground(new java.awt.Color(204, 204, 255));
        txtTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 210, 30));

        txtAutor.setBackground(new java.awt.Color(204, 204, 255));
        txtAutor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAutor.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 210, 30));

        txtEstatus.setBackground(new java.awt.Color(204, 204, 255));
        txtEstatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtEstatus.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 210, 30));

        txtEdicion.setBackground(new java.awt.Color(204, 204, 255));
        txtEdicion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtEdicion.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 210, 30));

        AGREGAR.setBackground(new java.awt.Color(51, 51, 255));
        AGREGAR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AGREGAR.setForeground(new java.awt.Color(255, 255, 255));
        AGREGAR.setText("AGREGAR");
        AGREGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AGREGARActionPerformed(evt);
            }
        });
        getContentPane().add(AGREGAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 110, 30));

        BUSCAR.setBackground(new java.awt.Color(51, 51, 255));
        BUSCAR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BUSCAR.setForeground(new java.awt.Color(255, 255, 255));
        BUSCAR.setText("BUSCAR");
        getContentPane().add(BUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 110, 30));

        MODIFICAR.setBackground(new java.awt.Color(51, 51, 255));
        MODIFICAR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MODIFICAR.setForeground(new java.awt.Color(255, 255, 255));
        MODIFICAR.setText("MODIFICAR");
        getContentPane().add(MODIFICAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 130, 30));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registroLibro/vista-superior-del-libro-en-el-viejo-fondo-del-tablon-de-madera-vintage-efecto-estilo-imagenes_1253-964.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SALIRActionPerformed

    private void cmAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmAnioActionPerformed

    private void AGREGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AGREGARActionPerformed
        PrintWriter salida = null;
        libro = new LibroBib(txtISBN.getText()+", ", 
                txtTitulo.getText()+", ", 
                txtAutor.getText()+", ", 
                cmDia.getSelectedItem().toString(),
                cmMes.getSelectedItem().toString(),
                cmAnio.getSelectedItem().toString()+", ",
                txtEstatus.getText()+", ",
                txtEdicion.getText());
        listaLibros.add(libro);
       
        try{
            File archivo = new File (txtTitulo.getText()+".txt");
            if(txtTitulo.getText()+".txt"!=txtTitulo.getText()+".txt"){
                salida = new PrintWriter(new BufferedWriter(new FileWriter(txtTitulo.getText()+".txt",true)));
                salida.println(libro);
                salida.close();
            }
            else{
                JOptionPane.showMessageDialog(null,"Error, el libro ya existe!"); 
            }
 
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error al escribir!"); 
        }
        finally {
            salida.close();
        }
        
    }//GEN-LAST:event_AGREGARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AGREGAR;
    private javax.swing.JButton BUSCAR;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton MODIFICAR;
    private javax.swing.JButton SALIR;
    private javax.swing.JLabel TITULO;
    private javax.swing.JComboBox<String> cmAnio;
    private javax.swing.JComboBox<String> cmDia;
    private javax.swing.JComboBox<String> cmMes;
    private javax.swing.JLabel lbAutor;
    private javax.swing.JLabel lbEdicion;
    private javax.swing.JLabel lbEstatus;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbISBN;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtEdicion;
    private javax.swing.JTextField txtEstatus;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
